# Generated by Django 5.1.1 on 2024-10-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=25)),
            ],
        ),
    ]
